[package]
name = "config-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
glib = "0.21.4"
gtk = "0.18.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
utils = { path = "../libs/utils" }

[profile.release]
lto = true
